name: Build Project

on:
  push:
    branches: ["mainline"]
  pull_request:
    branches: ["mainline"]

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyright pytest websockets zmq msgpack
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pyright
        run: |
          pyright
      - name: Test with pytest
        run: |
          pytest
        env:
          APCA_API_KEY_ID: "DUMMY_KEY_FOR_TESTING"
          APCA_API_SECRET_KEY: "DUMMY_SECRET_FOR_TESTING"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./data-ingestion/coverage.xml

  build-cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        compiler: [{ c: gcc, cpp: g++ }, { c: clang, cpp: clang++ }]

    steps:
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-get-${{ hashFiles('**/CMakeLists.txt') }} # A new cache if apt dependencies change
          restore-keys: |
            ${{ runner.os }}-apt-get-

      - uses: actions/checkout@v4
      - name: Install Latest CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.0.0
        continue-on-error: false

      - name: Install libraries - PkgConfig, Boost, QuantLib, CURL, OpenSSL, ZMQ
        id: install
        shell: bash
        run: |
          sudo apt-get update -y && \
          sudo apt-get upgrade -y && \
          sudo apt-get install pkg-config libboost-all-dev libquantlib0-dev libquantlib0v5 curl libcurl4-openssl-dev libssl-dev libzmq3-dev lcov

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: |
          CMAKE_CXX_FLAGS=""
          if [[ "${{ matrix.compiler.cpp }}" == "g++" && "${{ matrix.build_type }}" == "Debug" ]]; then
            CMAKE_CXX_FLAGS="--coverage"
          fi
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure

      - name: Generate C++ coverage report
        if: matrix.build_type == 'Debug'
        working-directory: ./build
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload C++ Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trading-engine-${{ matrix.os }}-${{ matrix.compiler.c }}-${{ matrix.build_type }}
          path: build/hello

      - name: Upload C++ coverage to Codecov
        if: matrix.compiler.cpp == 'clang++' && matrix.build_type == 'Debug'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.info
          fail_ci_if_error: true
